### ISSUE TITLE
Wiped out filesystem. 

### ISSUE THREAD

**Issue by sirsikes777** [handmade0octopus/factorio-linux-server#1]
Thanks for deleting the entire filesystem on my server. Can't tell if this was intentional or not. Just wanted to play some Factorio.

**Comment by handmade0octopus** [comment]
Oh man.. We use one command that is loaded from `config.sh` namely `sudo rm -fr $serverPath/*` which is what could cause this if server path is blank.. I need to add check to that one :0

**Comment by darkdelusions** [comment]
This issue also occurred to a friend and I when trying to setup a server.

**Comment by handmade0octopus** [comment]
Fixed in new release:https://github.com/handmade0octopus/factorio-linux-server/commit/87a52329ab22299d1a445b0854f2fd7c98ccc693

**Comment by CopyPasteAdmin** [comment]
The Wipe-Out happend to me today ...
